[package]
name = "test-game"
version = "0.1.0"
authors = ["Jack Fransham <me@jackfransham.com>"]

[[bin]]
name = "test"

[dependencies]
piston = "^0.10.1"
piston2d-graphics = "^0.9.0"
piston2d-opengl_graphics = "^0.12.0"
pistoncore-glutin_window = "^0.12.0"
